spark:
  app-name: Spark-kafka-Analyzer
  master: local[*]
  db-ip-type: spark.cassandra.connection.host
  db-ip: 127.0.0.1
  case-sensitive: false
  port-type: spark.cassandra.connection.port
  port: 9042

kafka:
  topic: test123

cassandra:
  keyspace-name: rsvp
  table-name: datacenter1

server:
  port: 8082
