server:
  port: 8081

spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        output:
          binder: kafka
          destination: test123
          group: output-group-1
          content-type: text/plain

connection:
  url: https://stream.meetup.com/2/rsvps
  timeout: 5000
  read-timeout: 50000

kafka:
  timeout: 10000

---

spring:
  profiles:
    - test

connection:
  url:
  timeout: 0
  read-timeout: 0

kafka:
  timeout: 0
